import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/app/section/navbar";
import "./globals.css";
import AOSProvider from "./AOSProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portofolio | Ezar Hardin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#18181b] text-white`}
        id="home"
      >
        <div className="container mx-auto px-6">
          <Navbar />
          <AOSProvider>{children}</AOSProvider>
        </div>
      </body>
    </html>
  );
}
